---
# Project information
site_name: Repo Racers
site_url: https://turbo-goldfish-j47gj56wq5wcrjx-8000.app.github.dev/
site_author: Repo Racers
site_description: >-
  Playbook and tooling for migrations to GitHub from
  other platforms and between GitHub instance types.

# Repository
repo_name: repo-racers
repo_url: https://github.com/iberian-space/repo-racers

# Copyright
copyright: Copyright &copy; 2024 Repo Racers

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  favicon: 'assets/images/favicon.ico'
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/github
  features:
    - navigation.tabs
    - navigation.footer

# Extra
extra:
  404: '404.md'

plugins:
  - search
  - termynal:
      prompt_literal_start:
        - "$"

# Page tree
nav:
  - Home: index.md
  - Our Playbook:
      - playbook/our_playbook.md
      - playbook/accessibility.md
      - Agile Guide:
          - playbook/agile_guide/scrumban.md
          - Basics:
              - Backlog Management: playbook/agile_guide/basics/backlog_management.md
              - Ceremonies: playbook/agile_guide/basics/ceremonies.md
              - Roles: playbook/agile_guide/basics/roles.md
              - Sprints: playbook/agile_guide/basics/sprints.md
          - How We Roll: playbook/agile_guide/how_we_roll/how_we_roll.md
          - Beyond The Basics:
              - Backlog Management: playbook/agile_guide/beyond_the_basics/backlog_management/backlog_management.md
              - Collaboration:
                  - playbook/agile_guide/beyond_the_basics/collaboration/collaboration.md
                  - Virtual Collaboration: playbook/agile_guide/beyond_the_basics/collaboration/virtual_collaboration.md
                  - Pair Programming: playbook/agile_guide/beyond_the_basics/collaboration/pair_programming.md
                  - Team Dynamics: playbook/agile_guide/beyond_the_basics/collaboration/team_dynamics.md
                  - Social Question: playbook/agile_guide/beyond_the_basics/collaboration/social_question.md
              - Crew Contracts:
                  - playbook/agile_guide/beyond_the_basics/crew_contracts/crew_contracts.md
                  - playbook/agile_guide/beyond_the_basics/crew_contracts/crew_manifesto.md
                  - playbook/agile_guide/beyond_the_basics/crew_contracts/working_agreement.md
                  - playbook/agile_guide/beyond_the_basics/crew_contracts/definition_of_ready.md
                  - playbook/agile_guide/beyond_the_basics/crew_contracts/definition_of_done.md
      - playbook/reliability/reliability.md
      - Security:
          - playbook/security/security.md
          - Threat Modelling: playbook/security/threat_modelling.md
          - Threat Modelling Example: playbook/security/threat_modelling_example.md
          - Rules of Engagement: playbook/security/rules_of_engagement.md
      - Source Control:
          - playbook/source_control/source_control.md
          - Git Guidance: playbook/source_control/git_guidance/git_guidance.md
          - Component Versioning: playbook/source_control/component_versioning.md
          - Merge Strategies: playbook/source_control/merge_strategies.md
          - Naming Branches: playbook/source_control/naming_branches.md
          - Secrets Management: playbook/source_control/secrets_management.md

  - Crew Contracts:
      - Crew Manifesto: crew_contracts/crew_manifesto.md
      - Definition of Ready: crew_contracts/definition_of_ready.md
      - Definition of Done: crew_contracts/definition_of_done.md
      - 12 Factor App Checklist: crew_contracts/12_factor_app_checklist.md
      - Azure Deployment Checklist: crew_contracts/azure_deployment_checklist.md
      - Code of Conduct: crew_contracts/code_of_conduct.md
  - Service Catalog:
      - service_catalog/service_catalog.md
  - Product Catalog:
      - product_catalog/product_catalog.md
  - Contributing To This Repository:
      - contributing/contribution_guidelines.md
      - Pre-Commit: contributing/pre_commit.md
  - Our Super Heroes:
      - our_heroes/our_super_heroes.md
  - Showcase:
      - showcase/bankrupt_britain.md
