---
# Project information
site_name: Repo Racers
site_url: https://turbo-goldfish-j47gj56wq5wcrjx-8000.app.github.dev/
site_author: Repo Racers
site_description: >-
  Playbook and tooling for migrations to GitHub from
  other platforms and between GitHub instance types.

# Repository
repo_name: repo-racers
repo_url: https://github.com/iberian-space/repo-racers

# Copyright
copyright: Copyright &copy; 2024 Repo Racers

# Configuration
theme:
  name: material
  favicon: 'assets/images/favicon.ico'
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/github
  features:
    - navigation.tabs
    - navigation.footer

plugins:
  - termynal:
      prompt_literal_start:
        - "$"

# Page tree
nav:
  - Home: index.md